# Regenerates Generated/BuildInfo.h + BuildInfo.cpp on every build.
# Invoked as: cmake -DPF_VERSION=... -DSRC_DIR=... -DOUT_DIR=... -P GenerateBuildInfo.cmake

if(NOT DEFINED PF_VERSION)
    set(PF_VERSION "0.0.0")
endif()
if(NOT DEFINED SRC_DIR OR NOT DEFINED OUT_DIR)
    message(FATAL_ERROR "GenerateBuildInfo.cmake requires SRC_DIR and OUT_DIR")
endif()

set(GIT_HASH "unknown")
set(GIT_DIRTY "")
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE AND EXISTS "${SRC_DIR}/.git")
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE GIT_STATUS
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(GIT_STATUS)
        set(GIT_DIRTY "+")
    endif()
endif()

string(TIMESTAMP BUILD_TIME "%Y-%m-%d %H:%M")
# ASCII separators only — middle-dot · often missing in host UI fonts.
set(STAMP "${PF_VERSION} | ${BUILD_TIME} | ${GIT_HASH}${GIT_DIRTY}")

file(MAKE_DIRECTORY "${OUT_DIR}")

file(WRITE "${OUT_DIR}/BuildInfo.h" [=[
#pragma once

namespace pflow::build_info {

/** Marketing / project version from CMake (e.g. "1.0.0"). */
const char* version();
/** Short git commit hash; trailing '+' if the working tree was dirty at build. */
const char* gitHash();
/** Local build timestamp "YYYY-MM-DD HH:MM". */
const char* buildTime();
/** Single line for testers: "1.0.0 | 2026-07-14 14:05 | a1b2c3d+". */
const char* stamp();

} // namespace pflow::build_info
]=])

file(WRITE "${OUT_DIR}/BuildInfo.cpp" "\
// Generated by cmake/GenerateBuildInfo.cmake — do not edit.\n\
#include \"BuildInfo.h\"\n\
\n\
namespace pflow::build_info {\n\
const char* version()   { return \"${PF_VERSION}\"; }\n\
const char* gitHash()   { return \"${GIT_HASH}${GIT_DIRTY}\"; }\n\
const char* buildTime() { return \"${BUILD_TIME}\"; }\n\
const char* stamp()     { return \"${STAMP}\"; }\n\
}\n\
")

message(STATUS "BuildInfo: ${STAMP}")
